# External configuration for UI defaults, model paths, and quality metric parameters.
# This file allows for easy tuning without modifying the application code.

# --- UI & Filter Defaults ---
# Default values for the Gradio user interface components.
ui_defaults:
  # --- Extraction Settings (New Workflow) ---
  thumbnails_only: True              # Recommended: Extract only thumbnails first. Full-res frames are extracted on-demand during export.
  thumb_megapixels: 0.5              # Target resolution for thumbnails (e.g., 0.5 = ~960x540 for a 16:9 video).
  scene_detect: True                 # Enable scene detection during extraction. Crucial for the new scene-based workflow.
  max_resolution: "maximum available" # Max resolution for video downloads (e.g., from YouTube).

  # --- Pre-Analysis & Seeding Settings ---
  pre_analysis_enabled: True         # Automatically analyze scene thumbnails to find the best frame for seeding.
  pre_sample_nth: 1                  # When pre-analyzing, check every Nth frame in a scene. 1 = all frames. Higher values are faster for long scenes.
  enable_face_filter: True           # Enable face similarity scoring (requires reference image).
  face_model_name: "buffalo_l"       # InsightFace model for face analysis.
  enable_subject_mask: True          # Enable subject masking and propagation.
  dam4sam_model_name: "sam21pp-L"    # DAM4SAM model for mask propagation.
  person_detector_model: "yolo11x.pt" # YOLO model for detecting persons.
  seed_strategy: "Reference Face / Largest" # Fallback strategy if text prompt or face match fails.
  text_prompt: ""                    # Global text prompt for seeding (can be overridden per-scene).

  # --- Final Analysis & Filtering ---
  resume: False                      # Attempt to resume a previous analysis run (less relevant in new workflow).
  require_face_match: False          # In final filtering, reject frames that have no face detected.
  enable_dedup: True                 # Enable perceptual hash-based near-duplicate removal during analysis.
  dedup_thresh: 5                    # pHash distance threshold for deduplication (lower is stricter).

  # --- Legacy Full-Frame Extraction Settings (used if 'thumbnails_only' is false) ---
  method: "all"
  interval: 5.0
  fast_scene: False
  use_png: True
  nth_frame: 5
  disable_parallel: False


# Central registry for all filter sliders and checkboxes.
# Used for component creation and reset behavior in the Filtering & Export tab.
filter_defaults:
  quality_score: { min: 0.0, max: 100.0, step: 0.5, default_min: 0.0, default_max: 100.0 }
  sharpness: { min: 0.0, max: 100.0, step: 0.5, default_min: 0.0, default_max: 100.0 }
  edge_strength: { min: 0.0, max: 100.0, step: 0.5, default_min: 0.0, default_max: 100.0 }
  contrast: { min: 0.0, max: 100.0, step: 0.5, default_min: 0.0, default_max: 100.0 }
  brightness: { min: 0.0, max: 100.0, step: 0.5, default_min: 0.0, default_max: 100.0 }
  entropy: { min: 0.0, max: 100.0, step: 0.5, default_min: 0.0, default_max: 100.0 }
  niqe: { min: 0.0, max: 100.0, step: 0.5, default_min: 0.0, default_max: 100.0 }
  face_sim: { min: 0.0, max: 1.0, step: 0.01, default_min: 0.5 }
  mask_area_pct: { min: 0.0, max: 100.0, step: 0.1, default_min: 1.0 }
  dedup_thresh: { min: -1, max: 32, step: 1, default: -1 } # -1 disables dedup in the filter tab UI by default

# --- Quality Metrics Configuration ---
# Weights for combining individual quality scores into a single quality score.
quality_weights:
  sharpness: 25
  edge_strength: 15
  contrast: 15
  brightness: 10
  entropy: 15
  niqe: 20

# Base scaling constant for sharpness, adjusted by image resolution.
# A higher value makes the score less sensitive.
sharpness_base_scale: 2500
edge_strength_base_scale: 100

# Minimum percentage of the frame area that a subject mask must occupy to be considered valid.
min_mask_area_pct: 1.0

# --- Model & Path Configuration ---
# Paths for models and other external dependencies.
model_paths:
  grounding_dino_config: "Grounded-SAM-2/grounding_dino/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  grounding_dino_checkpoint: "models/groundingdino_swint_ogc.pth"

# --- Grounded DINO/SAM2 Inference Parameters ---
grounding_dino_params:
  box_threshold: 0.35
  text_threshold: 0.25
